 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

model:
  arch: pretrain
  load_finetuned: False

  pretrained: "https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/BLIP2/blip2_pretrained_vitL.pth"
  # pretrained: "https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/BLIP2/rn50_checkpoint_pre.pth"
  # pretrained: "https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/BLIP2/checkpoint_7.pth"
  # pretrained: "https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/BLIP2/checkpoint_21.pth"
  # finetuned: "https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/BLIP2/checkpoint_23.pth"

  # vit encoder
  vit_model: "RN50x16"
  image_size: 640
  drop_path_rate: 0.0
  use_grad_checkpoint: False
  vit_precision: float
  freeze_vit: False
  max_txt_len: 12
  vision_width: 1024
  loss_itc_weight: 1
  cross_attention_freq: 2
  agg_method: 'hug_cross'
  


  # Q-Former
  num_query_token: 64


preprocess:
    vis_processor:
        train:
          name: "blip2_rn_image_train"
          image_size: 640
        eval:
          name: "blip_image_rn_eval"
          image_size: 640
    text_processor:
        train:
          name: "blip_caption"
        eval:
          name: "blip_caption"
